from count_vowels import count_vowels
from locating import locating_character
from mario_pyramid import simple_mario_pyramid,list_mario_pyramid
from multiplication_table import multiplication_table,multiplication_table_in_lists
from sort_array import sort_array
from user_and_email_validate import user_email_validate
from extract_domain import extract_domains
from email_validation import valid_username,valid_email,filtering_emails
from user_pass_check import user_pass_auth
from Data_test_samples import emails,user_list
